package com.tcpip147.jdirect.ffm.enums;

import lombok.AllArgsConstructor;

//@formatter:off
@AllArgsConstructor
public enum DWRITE_FONT_WEIGHT {
    DWRITE_FONT_WEIGHT_THIN(100),
    DWRITE_FONT_WEIGHT_EXTRA_LIGHT(200),
    DWRITE_FONT_WEIGHT_LIGHT(300),
    DWRITE_FONT_WEIGHT_SEMI_LIGHT(350),
    DWRITE_FONT_WEIGHT_NORMAL(400),
    DWRITE_FONT_WEIGHT_MEDIUM(500),
    DWRITE_FONT_WEIGHT_SEMI_BOLD(600),
    DWRITE_FONT_WEIGHT_BOLD(700),
    DWRITE_FONT_WEIGHT_EXTRA_BOLD(800),
    DWRITE_FONT_WEIGHT_BLACK(900),
    DWRITE_FONT_WEIGHT_EXTRA_BLACK(950)
	;

	public final int value;
}
